### PR TITLE
More tests

### PR DESCRIPTION
**Pull request by EvgeniiZaitsevCW**
Additional tests have been added.

The "solidity-coverage" hardhat plugin has been included in the project.
To get the coverage info run `hardhat coverage` after `npm install`, then go to the `coverage` directory and open the `index.html` file in your browser.

There are other ideas about improvements. They are the subject of other pull requests.

The current coverage info:
spin-machine-coverage-2022-01-21

### CODE REVIEW

**Review by arthur-cw — APPROVED** [review]
Looks correct to me.
Just one question @EvgeniiZaitsevCW why did you name the faucet mock contract as `faucetTraceableMock` and not `FaucetMock`?

**Comment by EvgeniiZaitsevCW** [comment]
> Looks correct to me. Just one question @EvgeniiZaitsevCW why did you name the faucet mock contract as `faucetTraceableMock` and not `faucetMock`?

@arthur-cw 
Good question.
Firstly I thought that "traceable" would show that we can somehow trace the state of the mock contract.
But currently, I think your version (`FaucetMock`) is better because it straightly corresponds (by the name) to the interface `IFaucet` and real `Faucet` contract.
I'll rename `FaucetTraceableMock` => `FaucetMock`

cc @IgorSenychCW

**Comment by EvgeniiZaitsevCW** [comment]
@IgorSenychCW, @arthur-cw 
I have added stand-alone tests for util contracts.
The appropriate duplicated tests have been removed from the spin machine contracts.
The screenshot in the description of this PR has been updated according to the new changes.
Please, review again.

**Comment by IgorSenychCW** [comment]
> > Looks correct to me. Just one question @EvgeniiZaitsevCW why did you name the faucet mock contract as `faucetTraceableMock` and not `faucetMock`?
> 
> @arthur-cw Good question. Firstly I thought that "traceable" would show that we can somehow trace the state of the mock contract. But currently, I think your version (`FaucetMock`) is better because it straightly corresponds (by the name) to the interface `IFaucet` and real `Faucet` contract. I'll rename `FaucetTraceableMock` => `FaucetMock`
> 
> cc @IgorSenychCW

I agree with @arthur-cw that, in this context, FaucetMock would be a better name.

**Pull request merged**
